#155 export toaster, fix stories + update IStep interface
OnroerendErfgoed/vue_component_library pull request #156
Opened 2023-11-13 13:51 UTC by yannickkuypers

Issue #155 

Wachten op het VEKA tot de EPC nummers terug werken zodat we dit kunnen testen

2023-11-13 15:00 UTC, wouter-adriaens requested changes

2023-11-13 15:09 UTC, yannickkuypers commented on src/models/wizard.ts
> +  validate: () => Promise<{ valid: boolean; error?: IToast }>;
Tgoh ja, akkoord. Langs de andere kant gaat dieje IStep wel enkel gebruikt worden voor wizards dus misschien is dat niet zo slecht dat we daar toasters verplichten zodat we die functionaliteit doortrekken?

2023-11-14 08:55 UTC, wouter-adriaens commented on src/models/wizard.ts
> +  validate: () => Promise<{ valid: boolean; error?: IToast }>;
Ok ja zo dwingen we misschien al wat consistentie af

2023-11-14 13:42 UTC, wouter-adriaens approved these changes

2023-11-14 13:50 UTC, merged