#157 resolve OESelect index error
OnroerendErfgoed/vue_component_library pull request #158
Opened 2023-11-13 14:32 UTC by yannickkuypers

Issue #157

2023-11-13 14:52 UTC, wouter-adriaens requested changes

2023-11-13 14:53 UTC, cedrikv commented on src/components/dumb/OeSelect.vue
> +        <template v-for="(option, index) in options" :key="'select-' + index">
en vergeet uwe linter niet te runnen hé

2023-11-14 10:15 UTC, wouter-adriaens approved these changes

2023-11-14 12:33 UTC, wouter-adriaens approved these changes

2023-11-14 12:33 UTC, merged