css tweaks
OnroerendErfgoed/vue_component_library pull request #160
Opened 2023-11-14 08:58 UTC by cedrikv

2023-11-14 12:30 UTC, roefem requested changes

2023-11-14 12:30 UTC, roefem commented on src/scss/_override-variables.scss
> +  margin: 0 auto;
dit breekt nog de layout bij kleinere screensize zie ik. Is het eigenlijk wel nodig om van de huisstijl af te wijken en dit menu te centreren? Full width ziet het er ook goed uit

2023-11-14 17:30 UTC, roefem submitted a review, later dismissed

2023-11-14 17:36 UTC, roefem commented on src/scss/_override-variables.scss
> +  margin: 0 auto;
bij toggelen van menu op de algemeen tab:
![image](https://github.com/OnroerendErfgoed/vue_component_library/assets/62388265/c5cad5a9-63f1-4130-a151-2328783f703b)

2023-11-14 17:46 UTC, roefem commented on src/scss/_override-variables.scss
> +  margin: 0 auto;
nvm dat is op te lossen in plannen zelf.

2023-11-14 17:53 UTC, roefem requested changes

2023-11-14 17:53 UTC, roefem commented on src/scss/_override-variables.scss
> +  align-items: center;
doet die align-items iets?

2023-11-16 14:03 UTC, cedrikv commented on src/scss/_override-variables.scss
> +  align-items: center;
k is wezg

2023-11-16 14:38 UTC, roefem approved these changes

2023-11-16 14:39 UTC, merged